name: Publish wiki

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'

jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          path: docs
        env:
          GH_TOKEN: ${{ secrets.WIKI_PUBLISH }}

